### ISSUE TITLE
A WORKING SOLUTION !!! 

### ISSUE THREAD

**Issue by brofist01** [ajdnik/decrypo#4]
#  **https://github.com/brofist01/Pluralsight-Decrypt.git**

**Comment by ajdnik** [comment]
Hi @brofist01,

I came across your tool when I was researching the topic of decrypting/decoding the videos but since I primarily use a MacOS I, unfortunately, couldn't use it. That's why I decided to build a cross-platform tool for both Mac and Windows devices.

I found a [great article](https://andorian.blogspot.com/2017/08/de-obfuscate-videos-from-pluralsight.html) that explains how to decrypt videos on MacOS and by using [ILSpy](https://github.com/icsharpcode/ILSpy) I was able to decompile the Pluralsight application on Windows which showed me how to decrypt it on Windows.

**Comment by ajdnik** [comment]
If you have any issues running the __decrypo__ tool on Windows system please let me know and I'll fix the problems if possible.
