### ISSUE TITLE
How do I use it on Mac without brew? 

### ISSUE THREAD

**Issue by subba16** [ajdnik/decrypo#6]

**Comment by ajdnik** [comment]
Hi @subba16,

you can download the binaries manually from the [GitHub's Releases](https://github.com/ajdnik/decrypo/releases) page and extract them to anywhere you like. Since you won't be using [Homebrew](https://brew.sh/) you'll need to make sure allow [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) to run this binary since it will block it by default. One way you can do that is by right-clicking it and clicking 'Open' that should trigger the Gatekeeper dialog where you can whitelist the binary.

The benefit of using [Homebrew](https://brew.sh/) is that it takes care of issues like that as well as it will enable you to upgrade the binary to newer versions once they will be released. If you'll go the manual route you'll also have to upgrade the binaries manually in the future by downloading them from GitHub and overriding your existing binary.
